import type { ShopItemDefinition } from "@prisma/client";

export type ShopItemSeed = Omit<
  ShopItemDefinition,
  "requiresAchievementId"
> & {
  requiresAchievementId?: string | null;
};

export const DEFAULT_AVATAR_KEY = "user";

export const SHOP_ITEMS: ShopItemSeed[] = [
  {
    id: "title-rookie",
    type: "TITLE",
    label: "Recruta LifeOS",
    description: "Para quem está a começar a jornada.",
    icon: "sparkles",
    price: 50,
    rarity: "COMMON",
    payload: "Recruta LifeOS",
    minLevel: 1,
    minPrestige: 0,
    sortOrder: 1,
  },
  {
    id: "title-grinder",
    type: "TITLE",
    label: "Máquina de Execução",
    description: "Título para operadores consistentes.",
    icon: "zap",
    price: 120,
    rarity: "COMMON",
    payload: "Máquina de Execução",
    minLevel: 5,
    minPrestige: 0,
    sortOrder: 2,
  },
  {
    id: "title-scholar",
    type: "TITLE",
    label: "Estudioso Noturno",
    description: "Honra sessões longas de estudo.",
    icon: "book-open",
    price: 150,
    rarity: "RARE",
    payload: "Estudioso Noturno",
    minLevel: 10,
    minPrestige: 0,
    sortOrder: 3,
  },
  {
    id: "title-closer",
    type: "TITLE",
    label: "Closer",
    description: "Para quem fecha negócios no Focus.",
    icon: "handshake",
    price: 300,
    rarity: "EPIC",
    payload: "Closer",
    minLevel: 20,
    minPrestige: 0,
    sortOrder: 4,
  },
  {
    id: "title-ceo",
    type: "TITLE",
    label: "CEO Aprendiz",
    description: "Ambição estratégica em progresso.",
    icon: "briefcase",
    price: 500,
    rarity: "EPIC",
    payload: "CEO Aprendiz",
    minLevel: 35,
    minPrestige: 0,
    sortOrder: 5,
  },
  {
    id: "title-legend",
    type: "TITLE",
    label: "Lendário Local",
    description: "Reconhecimento de elite na comunidade LifeOS.",
    icon: "crown",
    price: 900,
    rarity: "LEGENDARY",
    payload: "Lendário Local",
    minLevel: 50,
    minPrestige: 0,
    sortOrder: 6,
  },
  {
    id: "avatar-target",
    type: "AVATAR",
    label: "Caçador de Metas",
    description: "Avatar focado em objectivos.",
    icon: "target",
    price: 80,
    rarity: "COMMON",
    payload: "target",
    minLevel: 1,
    minPrestige: 0,
    sortOrder: 10,
  },
  {
    id: "avatar-flame",
    type: "AVATAR",
    label: "Forja de Hábitos",
    description: "Avatar para rotinas diárias.",
    icon: "flame",
    price: 100,
    rarity: "COMMON",
    payload: "flame",
    minLevel: 1,
    minPrestige: 0,
    sortOrder: 11,
  },
  {
    id: "avatar-book",
    type: "AVATAR",
    label: "Académico",
    description: "Avatar para perfis de estudo.",
    icon: "graduation-cap",
    price: 120,
    rarity: "RARE",
    payload: "graduation-cap",
    minLevel: 8,
    minPrestige: 0,
    sortOrder: 12,
  },
  {
    id: "avatar-briefcase",
    type: "AVATAR",
    label: "Negociador",
    description: "Avatar para finanças e clientes.",
    icon: "briefcase",
    price: 200,
    rarity: "RARE",
    payload: "briefcase",
    minLevel: 15,
    minPrestige: 0,
    sortOrder: 13,
  },
  {
    id: "avatar-swords",
    type: "AVATAR",
    label: "Dungeon Runner",
    description: "Avatar para desafios e dungeons.",
    icon: "swords",
    price: 350,
    rarity: "EPIC",
    payload: "swords",
    minLevel: 1,
    minPrestige: 0,
    sortOrder: 14,
  },
  {
    id: "avatar-crown",
    type: "AVATAR",
    label: "Monarca",
    description: "Avatar de prestígio elevado.",
    icon: "crown",
    price: 450,
    rarity: "EPIC",
    payload: "crown",
    minLevel: 30,
    minPrestige: 0,
    sortOrder: 15,
  },
  {
    id: "avatar-sparkles",
    type: "AVATAR",
    label: "Transcendente",
    description: "Desbloqueado após a primeira ascensão.",
    icon: "sparkles",
    price: 800,
    rarity: "LEGENDARY",
    payload: "sparkles",
    minLevel: 1,
    minPrestige: 1,
    sortOrder: 16,
  },
];
