-- Eventos de gamificação do módulo Finanças (F1.1)
ALTER TYPE "ActivityEventType" ADD VALUE 'FINANCE_METHOD_STEP';
ALTER TYPE "ActivityEventType" ADD VALUE 'FINANCE_REVIEW_COMPLETED';
ALTER TYPE "ActivityEventType" ADD VALUE 'FINANCE_GOAL_REACHED';
ALTER TYPE "ActivityEventType" ADD VALUE 'FINANCE_BUDGET_RESPECTED';
ALTER TYPE "ActivityEventType" ADD VALUE 'FINANCE_REVIEW_STREAK';
